# Railway nixpacks.toml para Node.js con Prisma
[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = [
    "npm ci --omit=dev",
    "npx prisma generate"
]

[phases.build]
cmds = [
    "npx prisma generate",
    "bash -lc 'if [ -d ../frontend ]; then cd ../frontend && npm ci --omit=dev && npm run build && mkdir -p ../backend/frontend-dist && cp -r dist/* ../backend/frontend-dist/; else echo "No frontend dir"; fi'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
APP_TIMEZONE = "America/Guayaquil"
TZ = "America/Guayaquil"
# CACHE_ENABLED=true por defecto. Si se adjunta Redis en Railway, exporta REDIS_URL.
