# Railway nixpacks.toml para Node.js con Prisma
[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = [
    "npm ci --omit=dev",
    "npx prisma generate"
]

[phases.build]
cmds = [
    "npx prisma generate",
    "npx prisma db push"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"