export { default as UAFEDashboard } from './UAFEDashboard';
export { default as UAFEKPICards } from './UAFEKPICards';
export { default as UAFEStatusPipeline } from './UAFEStatusPipeline';
export { default as UAFEProtocolTable } from './UAFEProtocolTable';
export { default as UAFEProtocolDetail } from './UAFEProtocolDetail';
export { default as UAFEReportPanel } from './UAFEReportPanel';
export { default as UAFEMinutaUpload } from './UAFEMinutaUpload';
export { default as UAFEPersonaEditDialog } from './UAFEPersonaEditDialog';
export { default as UAFEVehiculoForm } from './UAFEVehiculoForm';
export { default as SemaforoIndicator, SemaforoPersona } from './SemaforoIndicator';
export * from './uafe-constants';
